
language: objective-c

osx_image: xcode7.3

before_install:

    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --quiet
    - pod --version
    - pod setup --silent
    - pod repo update --silent

script:

    - pod lib lint --allow-warnings
    - xctool -workspace FlyImage.xcworkspace -scheme 'FlyImage' -sdk iphonesimulator -arch i386 build
    - xcodebuild -workspace FlyImage.xcworkspace -scheme 'FlyImageTests' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test
    