
language: objective-c

cache:
  - bundler
  - cocoapods

osx_image: xcode7.1

before_install:

    - export LANG=en_US.UTF-8
    - env
    - locale
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
    - pod --version
    - pod setup --silent > /dev/null
    - pod repo update --silent
    
script:

    - pod lib lint --allow-warnings
    - xctool -workspace FlyImage.xcworkspace -scheme 'FlyImage' -sdk iphonesimulator -arch i386 build
    
    - pod install --project-directory=Examples    
    - xctool -workspace './Examples/FlyImageView.xcworkspace' -scheme 'FlyImageView' -sdk iphonesimulator -arch i386 build
    - xctool -workspace './Examples/FlyImageView.xcworkspace' -scheme 'FlyImageIconView' -sdk iphonesimulator -arch i386 build
    - xctool -workspace './Examples/FlyImageView.xcworkspace' -scheme 'WebP' -sdk iphonesimulator -arch i386 build
    - xctool -workspace './Examples/FlyImageView.xcworkspace' -scheme 'SingleView' -sdk iphonesimulator -arch i386 build
    
    - xcodebuild -workspace FlyImage.xcworkspace -scheme 'FlyImageTests' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' test
                

    